### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by jqyp324** [TonnyL/Mango#16]
xception in thread "main" java.lang.NullPointerException: Couldn't find outer class io/github/tonnyl/mango/ui/main/MainPresenter$logoutUser$1$disposable$1 of io/github/tonnyl/mango/ui/main/MainPresenter$logoutUser$1$disposable$1$1

**Comment by jqyp324** [comment]
Exception in thread "main" java.lang.NullPointerException: Couldn't find outer class io/github/tonnyl/mango/ui/main/MainPresenter$logoutUser$1$disposable$1 of io/github/tonnyl/mango/ui/main/MainPresenter$logoutUser$1$disposable$1$1
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:1079)
	at com.google.devtools.build.android.desugar.ClassVsInterface.isOuterInterface(ClassVsInterface.java:56)
	at com.google.devtools.build.android.desugar.InterfaceDesugaring.visitOuterClass(InterfaceDesugaring.java:246)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:638)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:500)
	at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:477)
	at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:361)
	at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:314)
	at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:711)

**Comment by TonnyL** [comment]
Hi @jqyp324 ,

It seems somethings strange. Does this bug always appear when you try to log out?
